services:
  rabbit:
    image: rabbitmq:4-management-alpine@sha256:ac1201d1dc227779d93c607f976e7f9156fd5b551ee5ff7946cab6c242091bf3
    restart: unless-stopped
    networks:
      - app
      - frontend
    environment:
      - "RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}"
      - "RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}"
      - "RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}"
    volumes:
      - ".docker/data/rabbitmq:/var/lib/rabbitmq/mnesia/"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30

  supervisor:
    image: itkdev/supervisor-php8.4:alpine@sha256:e03a7ae707b83defdba16888a2e3f15d1c45b188af9c2f79db8a8d78b2aeec9c
    restart: unless-stopped
    stop_grace_period: 20s
    environment:
      - APP_SUPERVISOR_COMMAND=/app/bin/console messenger:consume --env=prod --no-debug --time-limit=900 --failure-limit=1 async
      - APP_SUPERVISOR_WORKERS=1
      - APP_SUPERVISOR_USER=deploy
      - PHP_MEMORY_LIMIT=256M
    networks:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
    depends_on:
      rabbit:
        condition: service_healthy

  phpfpm:
    depends_on:
      rabbit:
        condition: service_healthy
