services:
  rabbit:
    image: rabbitmq:4-management-alpine
    networks:
      - app
      - frontend
    ports:
      - "15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_ERLANG_COOKIE='local-dev-cookie-not-a-secret'
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30

  node:
    profiles:
      - dev
    image: node:24.0.1@sha256:222f704ce7f499c7bd7d101c993b980d86393e87bb54d416bcfcfe8e62aa9f64
    volumes:
      - .:/app
    working_dir: /app
