on: pull_request
name: Review
env:
    COMPOSE_USER: runner
jobs:
    validate-doctrine-schema:
        runs-on: ubuntu-latest
        name: Validate Doctrine Schema
        steps:
            - name: Checkout
              uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

            - name: Create docker network
              run: docker network create frontend

            - name: Install and validate
              run: |
                  docker compose up --detach
                  docker compose exec phpfpm composer install --no-interaction
                  docker compose exec phpfpm bin/console doctrine:migrations:migrate --no-interaction
                  docker compose exec phpfpm bin/console messenger:setup-transports failed
                  docker compose exec phpfpm bin/console doctrine:schema:validate

    phpstan:
        runs-on: ubuntu-latest
        name: PHPStan
        steps:
            - name: Checkout
              uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

            - name: Create docker network
              run: docker network create frontend

            - name: Run PHPStan
              run: |
                  docker compose run --rm phpfpm composer install --no-interaction
                  docker compose run --rm phpfpm vendor/bin/phpstan analyse

    phpunit:
        runs-on: ubuntu-latest
        name: PHP Unit tests
        steps:
            - name: Checkout
              uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

            - name: Create docker network
              run: docker network create frontend

            - name: Run tests with coverage
              run: |
                  docker compose up --detach
                  docker compose exec -e XDEBUG_MODE=coverage phpfpm composer install --no-interaction
                  docker compose exec -e XDEBUG_MODE=coverage phpfpm bin/console --env=test doctrine:database:drop --if-exists --force --quiet
                  docker compose exec -e XDEBUG_MODE=coverage phpfpm bin/console --env=test doctrine:database:create --no-interaction --if-not-exists --quiet
                  docker compose exec -e XDEBUG_MODE=coverage phpfpm bin/console --env=test doctrine:migrations:migrate --no-interaction --quiet
                  docker compose exec -e XDEBUG_MODE=coverage phpfpm vendor/bin/phpunit --coverage-clover=coverage/unit.xml

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  files: ./coverage/unit.xml
                  fail_ci_if_error: true
                  flags: unittests

    fixtures:
        runs-on: ubuntu-latest
        name: Load fixtures
        steps:
            - name: Checkout
              uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

            - name: Create docker network
              run: docker network create frontend

            - name: Load fixtures
              run: |
                  docker compose up --detach
                  docker compose exec phpfpm composer install --no-interaction
                  docker compose exec phpfpm bin/console doctrine:migrations:migrate --no-interaction
                  docker compose exec phpfpm composer fixtures

    build-assets:
        runs-on: ubuntu-latest
        name: Build assets
        steps:
            - name: Checkout
              uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

            - name: Create docker network
              run: docker network create frontend

            - name: Build assets
              run: |
                  docker compose run --rm node yarn install
                  docker compose run --rm node yarn build
